name: Push Nightly

on:
  # run every day at 11:15am
  schedule:
    - cron:  '15 11 * * *'

jobs:
  nightly:
    runs-on: linux.24_04.4x
    steps:
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: x64
      - name: Checkout TorchX
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          set -eux
          pip install -e .[dev]
          pip install twine
      - name: Run tests
        run: pytest --cov=./ --cov-report=xml
      - name: Push nightly
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: scripts/push_nightly.sh
